### ISSUE TITLE
Move Julia kernel, packages out of /home/jovyan

### ISSUE THREAD

**Issue by popensesame** [StochSS/stochss#1008]
See [this gitter convo](https://gitter.im/JuliaLang/julia?at=5f4fa25ad4f0f55ebbf9743a) and [this discourse question](https://discourse.julialang.org/t/system-wide-pkg-installation/1402)

**Comment by briandrawert** [comment]
This has already been done here: https://github.com/StochSS/stochss/blob/main/Dockerfile#L34
