### ISSUE TITLE
Asynchronous launching of compute nodes

### ISSUE THREAD

**Issue by choruk** [StochSS/stochss#103]
I know this is a change that is wanted so I decided to open this issue for it.

Unfortunately, this will be harder to accomplish than it might seem. Currently, the code actually spawns a new thread to handle the launching of the compute nodes asynchronously, however the end-user experience still feels like its synchronous. This behavior is due to how request lifetimes are treated in the app engine sandbox: basically app engine joins on all threads before returning a response from a request so there is no way to have any execution live past the end of the request. (see https://developers.google.com/appengine/docs/python/#Python_The_sandbox)

Well, that's not completely true actually. In order to achieve the asynchronous behavior we want, we can use an app engine API called background threads. (see https://developers.google.com/appengine/docs/python/backends/#Python_Background_threads) Background threads can only be spawned by Backends however, which require more configuration and amounts to another server running locally on the same machine as the actual StochSS app. This isn't exactly what they were designed for, but it *could* be done. (see https://developers.google.com/appengine/docs/python/backends/)

Not sure if it is really worth the effort/time. Any thoughts?

**Comment by bbbales2** [comment]
Fixed in 1.5
