### ISSUE TITLE
Upload .mdl does not refresh page 

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#1062]
To reproduce: In a project, click "add Model", select "Upload StochSS Model", upload a .mdl file, click 'Ok". Then nothing happens.  Page is un-changed, no success/failure messages.  

If you then click the browser reload button, the model will appear in the list of models.

**Comment by BryanRumsey** [comment]
This bog only applied to spatial model files (.smdl)

**Comment by briandrawert** [comment]
It occurred for me with 2 non-spatial models (Covid-19 .mdl files from the
repo)
