### ISSUE TITLE
Internal Server Error after logging into StochSS Live

### ISSUE THREAD

**Issue by benblamey** [StochSS/stochss#1370]
1. Login with Google authenication
2. Taken to https://live.stochss.org/hub/spawn
3.  I see:

500 : Internal Server Error
Error in Authenticator.pre_spawn_start: error nothing to repeat at position 0
You can try restarting your server from the [home page](https://live.stochss.org/hub/home).

4. Follow this link, i get taken to a page with "Start Server" button.
5. Click the button I am back to (2)

**Comment by BryanRumsey** [comment]
Thank you for reporting this, we have resolved the issue and login services are now up and running

**Comment by benblamey** [comment]
Great!
