### ISSUE TITLE
run.windows.py for Actual Windows Users

### ISSUE THREAD

**Issue by choruk** [StochSS/stochss#139]
There are new concerns with the run.windows.py script for actual windows users. It uses the ssh command to gain access to the EC2 instance and inject the admin token into the database. Windows doesn't come with ssh installed by default, so this won't work out of the box. Fortunately there is an OpenSSH implementation maintained for Windows users, which can be downloaded [here](http://miked.ict.rave.ac.uk/display/sshwindows/OpenSSH+for+Windows#OpenSSHforWindows-Downloads) and is very straightforward to install. It will ask what parts of the SSH package users want to install and we only need the SSH Client.

Another issue is the unusual location(s) that Python gets placed on Windows. The run.windows.py script calls out to another python script to handle the admin token exchange, so we need Windows users to add Python to their PATH. The alternative would be just to inline the contents of the second python script in run.windows.py, but its really not that hard to add Python to the PATH and it will make the windows users lives much easier (they can type *python run.windows.py* instead of *C:\Path\To\Python27\python run.windows.py*).

The process for adding Python to the PATH involves:
1. Open up *Control Panel*
2. Go to *System and Security*
3. Go to *System*
4. Go to *Advanced system settings*
5. Click on the *Environment Variables* button
Doing all of this will take you to a menu where you need to find the PATH variable, select it, and click the *Edit...* button to edit its value. In the textbox that appears, users will need to type *;C:\Python27* with their actual path to reach Python.

**Comment by bbbales2** [comment]
Run.windows.py needs to be verified on Windows

**Comment by ahellander** [comment]
And again, I’d like to push for renaming this to run.ec2.py, since that is actually what it is doing. It has nothing specific to do with windows.

/Andreas
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Mar 9, 2015, at 9:24 PM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Run.windows.py needs to be verified on Windows

**Comment by bbbales2** [comment]
Is this fixed by: https://github.com/StochSS/stochss/pull/542 ? Or does Windows support work yet?

**Comment by briandrawert** [comment]
Windows is now supported by our docker launcher.

**Comment by ahellander** [comment]
Now that we have “native” Windows support via docker, can we rename the old run.windows.py to the more descriptive run.ec2.py?



-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Mar 1, 2016, at 9:54 PM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:


Windows is now supported by our docker launcher.

**Comment by briandrawert** [comment]
Renaming here: https://github.com/StochSS/stochss/pull/567

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/pull/567
