### ISSUE TITLE
Python package dependencies

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#171]
I think we should use virtualenv and pip:

http://www.jontourage.com/2011/02/09/virtualenv-pip-basics/

That way, virtualenv is the only python package that the user must have installed to use our software, and then all the python dependencies can be installed through that.

Check out the very end of that blog post where the guy talks about dependencies.txt

There are still the regular dependencies that we have to handle

Comments? Objections?

The goal is to get rid of the libraries included by source and make using obscure-but-handy python packages not a problem

**Comment by briandrawert** [comment]
This is partially addressed in 5aaf8f4bffa749a260f1c328fb8975e7ad069b1e

**Comment by bbbales2** [comment]
Hopefully this is fixed by: https://github.com/StochSS/stochss/pull/542
