### ISSUE TITLE
Numpy 1.9 and FEniCS

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#249]
I upgraded my numpy to the latest version in pip (1.9) and started getting errors when importing dolfin like these guys ("ImportError: No module named oldnumeric"):
https://github.com/spectralpython/spectral/issues/13

I downgraded to numpy 1.8.2 and my dolfin went back to working.

Apparently oldnumeric has been removed, and my Fenics depended on it.

I checked the install scripts, and it looks like the run.ubuntu.sh ones use the package manager numpy, which is out of date.

I think on the Mac, the python in the devtools comes with an outdated numpy as well that seems to work.

Anyway, I think we're lucking out of hitting this problem now but maybe it's important later. I think Ubuntu 14.04 still uses numpy 1.8.1 so we're still safe.

**Comment by fogasawara** [comment]
Thanks for posting your comments!  

For an OSX 10.9.5 install with FEnICs 1.4.0 (version specifically requested) this fixed the following error:
"﻿Exception: Unable to import the Python Scientific module required by FIAT.
Consider installing the package python-scientific."

**Comment by bbbales2** [comment]
Oh okay so FEnICs 1.4.0 works for you? If so that's good to hear. Maybe this isn't a bug anymore

**Comment by fogasawara** [comment]
It is still a bug for OSX 10.9 with FEnICs 1.4.0 - your post gave me the clue on how to get dolfin to work with the FEnICs 1.4.0 OSX binary.  Thanks again!!!
