### ISSUE TITLE
Michaelis Menton Spatial model interpreting custom propensity as mass action

### ISSUE THREAD

**Issue by dbjnbnrj** [StochSS/stochss#262]
Start with Michaelis Menton example model

Convert to Spatial

Add diffusion coefficients + Mesh

Run simulation with default parameters

Get this error: "Reaction instance has no attribute 'marate'"

**Comment by bbbales2** [comment]
Fixed https://github.com/StochSS/stochss/commit/a3ba3b7ef03d68408d38eb0b4d655b60c68805f2

**Comment by ahellander** [comment]
Not so much a software question, but I am very skeptical about MM in spatial models, based on our new paper saying that you get very discretization dependent solutions.
