### ISSUE TITLE
1.5 Model editor scratchpad

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#292]
* ~~Use 'Custom mass action' instead of 'Mass action, custom stoichiometry'~~

**Comment by bbbales2** [comment]
* Put error messages in 3rd column for species/parameters
* 'Copy model to library' should forward user to the model editor page

**Comment by bbbales2** [comment]
* Edit buttons for models (no model selected by default)
* Show model name somewhere in title on page
* Add new model/add new reaction should be a single dropdown button
* Adds for parameters and species gonna just be buttons
* When adding anything new, change focus to 'name' field
* When selecting model to edit, close model editor collapsible and open the others

**Comment by gmy** [comment]
In "reaction editor", when I click "add" button it creates a new reaction and does the auto saving of the settings all the time. However, in other editors, the "add" button submit/confirm the addition. The two different adds seem to be a little bit inconsistent to me...

**Comment by briandrawert** [comment]
Import and Export links seem to have random order. How about:
- Load / Save Model
  - Import Model (XML/Zip)
  - Export Model (XML/Zip)
- Public Library
  - View Public Library
  - Export Model to Public Library

**Comment by briandrawert** [comment]
Under "Select  Model", the type, is really properties.  So rename header "type" -> "Properties"

**Comment by bbbales2** [comment]
* Upload mesh without subdomains blowing up (just generate subdomains server side)
* Import model mesh does not have unique name
* Change left right arrows to text
* Add birthdeath, dimer decay, lotka volterra, cylinder demo models to public library
* Hide export/import tools when no model selected

**Comment by bbbales2** [comment]
* Unlock products on set reaction types

**Comment by bbbales2** [comment]
* If model isn't select the little status message box isn't showing up

**Comment by bbbales2** [comment]
* Add mesh dimensions to example files!

**Comment by ahellander** [comment]
Spatial species editor: "Species allowed in these subdomains" -> "Active in subdomain"

**Comment by ahellander** [comment]
Spatial model cylinder demo: 
All reactions are set to "Custom Mass action", although they all match a more specific type.

**Comment by ahellander** [comment]
Everywhere in the model editor: "Specie->Species". I have never seen it written like the former. Is that the singular form?

**Comment by bbbales2** [comment]
Specie isn't valid. Just lemme know where that pops up.

Ben

**Comment by ahellander** [comment]
Mesh preview: The black mesh is hard to look at, strains the eye. Dark blue is a frequently used color. I vote change to that as default.

**Comment by ahellander** [comment]
Mesh preview: The controls panel in the top looks off from the rest of the design. Can you try to find colors/buttons that matches the color theme of the bootstrap templates? There are nice buttons/icons in bootstrap that one can use.  This is not a major issue, but it stands out from the rest of the design.

**Comment by ahellander** [comment]
Cloud computing page:
"Since there is no node running, need to choose at least one head node and zero or more follow-up nodes." -> "Since there is no node running, you need to choose at least one head node and zero or more compute nodes."

**Comment by ahellander** [comment]
Cloud computing page: 
The table with instance types does not collapse gracefully. One can not see that there are more options. 
![screen shot 2015-02-16 at 8 14 12 pm](https://cloud.githubusercontent.com/assets/2364390/6217846/9048bc24-b618-11e4-908d-e3ab647a9b4c.png)

**Comment by shellander** [comment]
In model editor: The list of reactions doesn't include A+B->C.

**Comment by shellander** [comment]
When I change the size of the window, weird things happen to the model editor. Consider setting a minimum width of the containing element.

![modeleditor16feb](https://cloud.githubusercontent.com/assets/3231282/6217905/b57f170e-b5cd-11e4-9ab5-0e514179ec5b.png)

**Comment by ahellander** [comment]
Cloud computing page:
1. It is not clear what is being launched by "One compute node at a time".
2. Advanced option: Can you include a short explanation for the flavors if you hover over the name? 
3. Why these specific flavors? Why not all the ones in the c3 line? Isn't the m3 line memory optimized? Do we need that. 
4. t1.micro makes me nervous with spatial models. 

I understand that this is not really bugs, but I worry that users will be very confused here.

**Comment by ahellander** [comment]
Running job in the cloud fails: 
"Cloud execution failed: cannot import name entry_to_queue "

**Comment by shellander** [comment]
In Job Summary->Trajectory select. It would be easier if the species were listed in the same order as in the model definition. You can also delete the commas.

**Comment by shellander** [comment]
When I launch a simulation of a deterministic model with sensitivity analysis, everything appears to be working (the 'Running job locally' box pops up), but the job is not listed under 'Job Status'.

**Comment by shellander** [comment]
Maybe turn off auto-complete for AWS credentials?

**Comment by ahellander** [comment]
I have a large number of old volumes in my EC2 account from old StochSS deployments. I need a warning somewhere to clean them up. They incur cost.

**Comment by ahellander** [comment]
Cloud computing page. 

I should not have to stop all nodes if I have many deployed of different flavors.

**Comment by shellander** [comment]
I can't launch Amazon compute nodes. Status is 'Pending: 1', and doesn't change.

![cloud16feb](https://cloud.githubusercontent.com/assets/3231282/6218200/b0abe862-b5d0-11e4-910d-dd8fb0f3aa29.png)

**Comment by shellander** [comment]
Simulation manager: Maybe change 'Units' to 'Type'?

**Comment by shellander** [comment]
The following should result in some kind of error message, but doesn't:

![stochoptim1](https://cloud.githubusercontent.com/assets/3231282/6218274/7d481c2e-b5d1-11e4-9a1a-3d6116d8b41b.png)

The model is empty (no species, no parameters, no reactions)...

The job is not listed in 'Job Status'.

**Comment by shellander** [comment]
Job Status: 'Deterministic/Stochastic' includes everything (spatial stochastic is also stochastic). Change to 'Non-spatial'.

**Comment by ahellander** [comment]
Cloud computing page: 
Statuses:
Creating Number: 1 
   Pending Number: 1 

should not be shown in red. They are not failed statuses. I suggest yellow, orange.

**Comment by ahellander** [comment]
Cloud computing page: 
I clicked "add one at a time" two times with just a short delay in between, I now have one started and one in Creating Number: 1 . In my EC2 dashboard, I have no instances spawning or failed
![screen shot 2015-02-16 at 8 57 16 pm](https://cloud.githubusercontent.com/assets/2364390/6218398/b9bc8a12-b61e-11e4-81b7-4bb8e8675bdc.png)
.

**Comment by ahellander** [comment]
Cloud computing page. Language issue:
 "Successfully requested starting virtual machines. Processing request... "
 "Successfully requested X virtual machines. Processing request... "
Where X is the number of requested machines. Alternatively, just 
 "Successfully requested virtual machines. Processing request... "

**Comment by ahellander** [comment]
Public library: Put the "Vilar oscillator back". The non-spatial stochastic models we have there are really really boring :-)  Oscillations are fun.

**Comment by ahellander** [comment]
StochOptim: 
Could we add a link to the document that describes the format? 
"1. Upload initial conditions data in tab separated format:"

**Comment by bbbales2** [comment]
Does it change after you refresh the status? Or just never?

Ben

**Comment by shellander** [comment]
It never changes.

2015-02-17 10:24 GMT-08:00 bbbales2 <notifications@github.com>:

**Comment by ahellander** [comment]
Mesh controls explanation shown even when no data is rendered, and it is in the wrong well. See screenshot. It does not seem to belong in "Metadata
![screen shot 2015-02-17 at 8 33 10 pm](https://cloud.githubusercontent.com/assets/2364390/6235704/9b782d1a-b6e4-11e4-869d-e103e3f5b90e.png)
"

**Comment by ahellander** [comment]
Job status page: Change the title "Result Analysis and Reproduction" -> "Result" (Too long, too much info at that level.)

**Comment by briandrawert** [comment]
In the model editor, create a mass-action reaction, then change it to "custom propensity', then change it back.  Model becomes invalid

**Comment by briandrawert** [comment]
Reaction species selector can have duplicate values if a species name is blank:
![ss2](https://cloud.githubusercontent.com/assets/1413538/6241649/d68f6508-b6d5-11e4-9713-df95cefd93ed.png)
![ss1](https://cloud.githubusercontent.com/assets/1413538/6241650/d691b01a-b6d5-11e4-9b63-31b1303a4b22.png)

**Comment by briandrawert** [comment]
When adding a new model, the model select box collapses before I can enter a name. Instead it is given a default name "model5". I have to click "select model" to change the name.
