### ISSUE TITLE
Three.JS rendered windows grab scroll-down events when not in focus

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#296]
On the model editor page, when scrolling down the page, the mesh pre-view stops the scrolling process and starts zooming out instead.  This is not the correct behavior.

**Comment by dbjnbnrj** [comment]
Resolved in develop

commit 8f1dfac1c6b06204813519024374e2cb60fce7d1
Author: dbjnbnrj <dbjnbnrj@gmail.com>
Date:   Wed Feb 18 10:44:11 2015 -0800

    Only noZoom enabled
