### ISSUE TITLE
StochSS 1.5, testing issues

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#299]
This is a list of issues found during testing, please make a comment with your issue, but do not close.

**Comment by briandrawert** [comment]
When the browser window is too narrow, you can not see the controls to launch all the instance types.  Also the "Status of VMs" tables breaks out of the main box:

![ss](https://cloud.githubusercontent.com/assets/1413538/6306332/6519db9c-b8e7-11e4-9f66-8dd2632ed789.png)

**Comment by shellander** [comment]
I still have the same problem on my mac (with Yosemite). 
![screen shot 2015-02-20 at 10 30 41 am](https://cloud.githubusercontent.com/assets/3231282/6306832/8ddf3726-b8eb-11e4-891b-5b97f49dc385.png)

**Comment by shellander** [comment]
Something doesn't work quite right when I try to rotate the E. Coli mesh. It appears I can't rotate it around one of the axis?

Also, it would be good to specify the exact volume of the E. Coli mesh, as the description doesn't uniquely determine the volume.

**Comment by dbjnbnrj** [comment]
Auto-rotation as a feature has been disabled for now. It can be enabled if this is an issue. Can you turn it via the controls?

**Comment by shellander** [comment]
What I mean is that I can't rotate the mesh around the z-axis (green axis) in the figure below:

![rotation](https://cloud.githubusercontent.com/assets/3231282/6307069/cfb5aa70-b8ed-11e4-8223-1aec3bf6444d.png)

By moving the mouse right to left I would expect rotation around the z-axis.

**Comment by bbbales2** [comment]
I'm not sure why it doesn't turn either. It's been like that as long as
we've had that mesh.

**Comment by shellander** [comment]
The mesh preview window doesn't expand when I make the window wider. That is, if I load a model in a narrow window, and then make it wider, it looks like this:
![mesh_window](https://cloud.githubusercontent.com/assets/3231282/6307241/1c21cbc2-b8ef-11e4-8289-11ba5896c875.png)

**Comment by shellander** [comment]
When I enter a job id that doesn't exist, I get the following screen instead of an error message:

![job_status](https://cloud.githubusercontent.com/assets/3231282/6307293/7eb8d190-b8ef-11e4-994f-8d093baaebcf.png)

**Comment by shellander** [comment]
When clicking 'cylinder_demo' in the metadata field in the job summary, I assume that I'm supposed to be directed to the model editor with the cylinder_demo pre-selected. This doesn't work for me, the link takes me to the model editor, but without selecting a model to edit.

**Comment by shellander** [comment]
The 'Example Library' link on the startup-page does not take me to the 'Example Library', but to the model editor.

**Comment by shellander** [comment]
I think that it would make sense to show http://www.stochss.org/wordpress/?cat=7&feed=rss2 on the startup page.

**Comment by JohnAbel** [comment]
When you import a model with custom propensity functions, it might be nice to have those posted in the reaction propensity function text box instead of being blank. To be clear, the model still runs fine. But you can't see what the propensity function is for the import
![screenshot from 2015-02-20 14 24 11](https://cloud.githubusercontent.com/assets/2702272/6310493/4ebb679c-b90c-11e4-801a-8975b165e8d7.png)
.

**Comment by bbbales2** [comment]
Hahaha, "It might be nice" this is definitely a bug.

**Comment by bbbales2** [comment]
Can you e-mail me the model?

**Comment by JohnAbel** [comment]
model sent.

when converting concentration, there should be some volume option, otherwise any concentration under 1 goes to 0. the conversion should be population = int(vol*concentration), not int(concentration). this should also be factored into rate parameters.
![screenshot from 2015-02-20 14 50 22](https://cloud.githubusercontent.com/assets/2702272/6310825/d608fec8-b90f-11e4-860c-15948c00bb39.png)

**Comment by JohnAbel** [comment]
(i actually can't further check it due to the SSA warning. SSA being steady-state approximation? slow-scale assumption? surprised i dont know this

**Comment by bbbales2** [comment]
There is a volume box down there by the Finish Conversion button.

A failure to convert doesn't prevent the conversion, it just means there
was some sort of error.

Oh man those are simple eqs. triggering the error... They definitely
shouldn't.

Ben

**Comment by JohnAbel** [comment]
Oh whoops I see the volume now, cool. Yeah all the rates are 1 or 10, so that should work

**Comment by bbbales2** [comment]
Fixed John's custom equation bug in latest. I also fixed an issue where you
could import things with invalid names

**Comment by bbbales2** [comment]
I fixed the model conversion bugs. So the model converter can use the
template types now

**Comment by bbbales2** [comment]
By the way could I call the 'ssa' assumptions the 'Gillespie' assumptions
and make it any clearer?

**Comment by briandrawert** [comment]
When deleting all the models in the system, the last model remains 'selected':
![ss](https://cloud.githubusercontent.com/assets/1413538/6322511/b24efaac-baca-11e4-8717-2144df7c76ff.png)

**Comment by briandrawert** [comment]
If a model fails, then cost-analysis and reproduction should be disabled.
![ss](https://cloud.githubusercontent.com/assets/1413538/6322764/26e15c6a-bad1-11e4-8af0-152f419a4752.png)

**Comment by bbbales2** [comment]
After compute nodes have been killed by the auto-timeout timer, I see them
on the cloud computing page until I load it twice.

So the first time I go there I see them, and then after I refresh they
disappear.

**Comment by JohnAbel** [comment]
I think I've found an issue in the conversion between deterministic and stochastic, Ben what are you up to today? specifically the conversion is fine but if you convert back to determinstic and run a concentration simulation it is wrong

**Comment by JohnAbel** [comment]
perhaps not this release, but there should be a way to change the volume without having to re-enter the entire model and convert it again
