### ISSUE TITLE
Stochoptim file format

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#302]
Currently there is a 'weight' column in the Stochoptim trajectories file that we do not document.

Look at the example files. Stochoptim can do something with this column but we don't say what.

**Comment by bbbales2** [comment]
Bernie reports that the 'weight' column is required by Stochoptim. So if it is going to be removed by us StochSS-side, we have to add it back before we pass the file to Stochoptim.

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/commit/1e8c9facd9cad117db1dbedf5d01af4565a90199

**Comment by briandrawert** [comment]
Closed in https://github.com/StochSS/stochss/pull/368
