### ISSUE TITLE
Alarm stopping a head-node

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#306]
It is inconvenient that the alarm stops a VM that hosts the webserver, strated by run.windows.py. And the CLI 'run.windows.py start' then failed to  bring that same instance back. Maybe we need to treat worker nodes and the server differently? 

Here is the error:
Enter an AWS EC2 instance ID that you wish to launch, 'None' to create a new instance, or hit return to use i-ecdcaf03: 
Launching EC2 instance from instance ID 'i-ecdcaf03'. This may take a moment...
Instance 'i-ecdcaf03' has state 'pending'
Instance 'i-ecdcaf03' has state 'pending'
Instance 'i-ecdcaf03' has state 'running'
Setting alarm to stop instance after 4 hours of idle cpu.
Attempting to start StochSS on 'ec2-23-20-217-18.compute-1.amazonaws.com'
Traceback (most recent call last):
  File "run.windows.py", line 766, in <module>
    main(sys.argv[1])
  File "run.windows.py", line 752, in main
    start_stochss_server(aws_access_key, aws_secret_key, preferred_instance_id, preferred_ec2_key_pair, ec2_region)
  File "run.windows.py", line 535, in start_stochss_server
    instance = ec2_services.launch_ec2_instance(preferred_instance_id, preferred_ec2_key_pair, keyfile=path_to_key_pair)
  File "run.windows.py", line 319, in launch_ec2_instance
    self.start_stochss_via_ssh(keyfile, instance.public_dns_name)
  File "run.windows.py", line 345, in start_stochss_via_ssh
    if not os.path.exists(keyfile):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by bbbales2** [comment]
Possibly addressed, needs to be checked

**Comment by briandrawert** [comment]
We are no longer using run.windows.py.  Closing
