### ISSUE TITLE
Spatial data export in human readable format

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#313]
Right now the spatial output is stored in pickle format that is really only compatible with StochSS. We need to add an export feature that dumps data as csv or something. A button on the results page would be suitable.

**Comment by ahellander** [comment]
I have a script I made for the tutorial at CSHL that reads the datafile from a StochSS result and creates output in XDMF
http://www.xdmf.org/index.php/XDMF_Model_and_Format

which can be loaded in e.g. Paraview to make movies etc. This is very useful, but not a lightweight operation if there is a lot of data. I think it would be suitable to have a dropdown on the result page where it is now a button that says download data, where one can choose format (raw, xdmf) etc.

**Comment by bbbales2** [comment]
We decided to have three export options:

1. The current pickle dump
2. A vtk export
3. A csv text format

**Comment by bbbales2** [comment]
I think this is fixed. (tested in https://github.com/StochSS/stochss/pull/546 at least ... I don't know where the fixes were actually made)
