### ISSUE TITLE
Cloud table on export page

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#315]
It's not clear what the table on the export page is for (it's for selectively getting stuff out of the cloud).

This table should also mirror the semantics of the status and import pages. That is, deterministic and stochastic separate from sensitivity

**Comment by briandrawert** [comment]
I think this fix broke the 'tabbing' of the page:
![ss1](https://cloud.githubusercontent.com/assets/1413538/7544216/016ddfe6-f580-11e4-98f4-fecdadbd35da.png)

**Comment by bbbales2** [comment]
Hmm, I'll check this out again. I was getting that behavior but thought I fixed it.

**Comment by bbbales2** [comment]
Try again, this should be fixed in https://github.com/StochSS/stochss/commit/289feba256fbd9cd289214a3f01ff44c20b0c375

**Comment by briandrawert** [comment]
Fixed in https://github.com/StochSS/stochss/commit/289feba256fbd9cd289214a3f01ff44c20b0c375
