### ISSUE TITLE
Ecoli mesh

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#317]
Something doesn't work quite right when I try to rotate the E. Coli mesh. It appears I can't rotate it around one of the axis?

**Comment by briandrawert** [comment]
I am still getting a vertical e.coli mesh, even after reseting my datastore.

**Comment by bbbales2** [comment]
Confirmed. There were two sets of xmls in StochSS. The ones visible to the user in the examples folder and then a second set hidden inside app/static/spatial. Updated the app/static/spatial e-coli mesh in https://github.com/StochSS/stochss/commit/007350c0b9b22db42d4e48227b8a1c9ad7ac0836

**Comment by briandrawert** [comment]
Fixed with https://github.com/StochSS/stochss/pull/380
