### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#319]
There are numerous places in the application where making the window small causes things to break out of boxes and look weird. Image from Stefan attached.

![](https://cloud.githubusercontent.com/assets/3231282/6217905/b57f170e-b5cd-11e4-9ab5-0e514179ec5b.png)

**Comment by briandrawert** [comment]
This is still an issue:
![ss1](https://cloud.githubusercontent.com/assets/1413538/7543668/2989028a-f57b-11e4-9b89-b1557f21ee30.png)
![ss2](https://cloud.githubusercontent.com/assets/1413538/7543670/2cefa3de-f57b-11e4-89c8-a307d6e91f8f.png)

**Comment by bbbales2** [comment]
Yeah I guess I didn't fix it as much as do something so that everything doesn't just explode.

**Comment by briandrawert** [comment]
I think the behavior is improved (if not eliminated) in https://github.com/StochSS/stochss/pull/368
