### ISSUE TITLE
Output storage in .app interfering with Mac OS X Firewall

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#329]
We're frequently changing files inside the Mac .app. This causes the Mac OS X Firewall to emit tons of "do you want to accept incoming connections to Python" messages as the application is used.

Look here: https://github.com/StochSS/stochss/pull/328

And here: http://superuser.com/questions/100013/why-does-the-mac-os-x-firewall-dialog-recurringly-pop-up-and-disappear-by-itself

**Comment by ahellander** [comment]
I propose making the place where we store output files a folder outside the app, and also configurable. Or will that risk making the thing less robust?

**Comment by bbbales2** [comment]
This should get fixed by https://github.com/StochSS/stochss/pull/546
