### ISSUE TITLE
Export of spatial result data in VTK and CSV format

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#330]
The output of a spatial job should be viewable in standard spatial data formats (VTK) as well as raw data (CSV) for analysis by the users.  Need buttons on the spatial output page to download these formats.

**Comment by bbbales2** [comment]
VTK issues should be addressed in https://github.com/StochSS/stochss/commit/a1e4467fe8deddf9ae1865569002e7dd859b2d31

**Comment by briandrawert** [comment]
Closed in https://github.com/StochSS/stochss/pull/368
