### ISSUE TITLE
Redundant model naming error

### ISSUE THREAD

**Issue by JohnAbel** [StochSS/stochss#333]
If you don't change the first model you make and leave it named 'model1', when you go to make a new model, it gives an error. Not sure if this is important or not, but it might be nice to detect.

**Comment by bbbales2** [comment]
Do you mind coming by a couple minutes before group meeting and trying to reproduce this with me tomorrow?

**Comment by JohnAbel** [comment]
Unfortunately not going to be at group meeting/in California tomorrow. It's
not super important to fix. Try it by just making some model and saving it
without changing the name, then going to a different tab and then back to
create a new model.

On Wed, Apr 22, 2015 at 4:50 PM, bbbales2 <notifications@github.com> wrote:

> Do you mind coming by a couple minutes before group meeting and trying to
> reproduce this with me tomorrow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StochSS/stochss/issues/333#issuecomment-95369789>.
>



-- 

*John H. Abel*
PhD Student, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu
Tel: (401)787-4253

**Comment by briandrawert** [comment]
I can not reproduce this error either.

**Comment by JohnAbel** [comment]
reloaded stochss and it went away ¯\_(ツ)_/¯
