### ISSUE TITLE
Width of the window should have a minimum size

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#335]
![screenshot from 2015-04-22 13 21 51](https://cloud.githubusercontent.com/assets/1413538/7300059/959d7346-e98e-11e4-923b-c8fac1d9bf38.png)

**Comment by briandrawert** [comment]
Is this a duplicate of https://github.com/StochSS/stochss/issues/319 ?

**Comment by bbbales2** [comment]
I believe so.
