### ISSUE TITLE
Explain the Gillespie-SSA assumptions

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#338]
![screenshot from 2015-04-22 13 46 57](https://cloud.githubusercontent.com/assets/1413538/7300312/5cc8d892-e990-11e4-8ae8-9d5f6b83812d.png)

**Comment by bbbales2** [comment]
Change text to:

"for mass action reactions with two or less reactants"

**Comment by briandrawert** [comment]
Fixed in b4335edb105c10a78f9b2e4cbccebb118001e231
