### ISSUE TITLE
Deterministic + Sensitivity jobs not performing mass action checks correctly

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#340]
When I model with an invalid mass action reaction is executed with the deterministic option, an error is produced.

Error: Reaction: A mass-action reaction cannot involve more than two of one species or one of two species. 

Deterministic + Sensitivity should show this error as well

**Comment by bbbales2** [comment]
This also applies to Stochoptim jobs

**Comment by briandrawert** [comment]
This is also #346. closed in https://github.com/StochSS/stochss/pull/352
