### ISSUE TITLE
Need to change spelling of 'specie' to 'species' in initial conditions editor

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#343]

**Comment by shellander** [comment]
Specie->Species

![screenshot from 2015-04-23 10 23 34](https://cloud.githubusercontent.com/assets/3231282/7303112/1b88f85e-e9a3-11e4-99fa-b7948cc96ec5.png)

**Comment by briandrawert** [comment]
Fixed in 4e6ade12c1e839157df00336c459b1e4142fda4e
