### ISSUE TITLE
Buffer larger number of images

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#356]
As I watch the output animate, it stops to buffer at 25 and 50. This shouldn't happen

**Comment by bbbales2** [comment]
This was just an issue with large output files. So the server was taking a long time to load the whole output trajectory and serve small pieces to the client.

If the size of the buffer window is increased maybe the server won't cause delays?

**Comment by dbjnbnrj** [comment]
Buffer size is now set using:

cacheRange = (maxLimit  < 50 ? maxLimit: 50);

**Comment by dbjnbnrj** [comment]
Buffering greater number of frames is resulting in greater time for the mesh to load. Keeping this to 25 for now.

**Comment by briandrawert** [comment]
It it is possible, can we make that a user controlled parameter?  Like and 'advanced' link that allows the user to specify the size.  I can see different situation/models that will require different sized buffers.

**Comment by bbbales2** [comment]
Do you have any ideas what the bottleneck in this process is?

25 frames vs. 50 frames in any of the example models should be like 20kb vs. 40kb. Maybe it doesn't have to be slow?

**Comment by bbbales2** [comment]
Checked

**Comment by briandrawert** [comment]
Fixed in #354
