### ISSUE TITLE
Animation scrollbar

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#358]
When I click the scrollbar while the animation is running, the animation keeps pulling it back to where it was.

I think I'd rather have the animation automatically stop and the bar scroll to where I clicked.

**Comment by bbbales2** [comment]
After the animation runs, going back to timepoint zero seems to confuse the scrollbar. I get "Loading..." text and nothing seems to happen.

Going to other timepoints is fine

**Comment by bbbales2** [comment]
Check boundary cases for animation.

For instance, with a 3 frame animation (0, 1, and 2) sometimes when the animation is at 2 it shows the frame at 1

**Comment by dbjnbnrj** [comment]
#27d97a7  - User can run from any timepoint

**Comment by bbbales2** [comment]
Checked

**Comment by briandrawert** [comment]
Fixed in #354
