### ISSUE TITLE
StochSS defaults to port 8080 on start-up

### ISSUE THREAD

**Issue by dbjnbnrj** [StochSS/stochss#365]
By default StochSS opens in port num 8080, which may be occupied. User should be able to start StochSS from a random unused port. 

Tested on StochSS run in Ubuntu currently.

Also npm modules are not auto installed in master branch as of now. Would be useful to trigger an npm install and watchify from the setup script itself.

**Comment by briandrawert** [comment]
Duplicated by #1083
