### ISSUE TITLE
Cloud jobs fail if maximum number of bucket used on S3 (was: Stochoptim not working in Cloud)

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#370]
Cloud Stochoptim isn't working for me on branch 'fixmasterstochoptim'

INFO     2015-05-09 20:04:54,693 stochoptim.py:604] Found running stochoptim job with S3 output: https://s3.amazonaws.com/stochss-output-005305b4-7b38-43eb-b11a-0d23c0d4814a/output/85a11443-a781-4d79-9812-4bf983bbde48.tar
INFO     2015-05-09 20:04:54,698 backendservice.py:506] fetchOutput: inside method with taskid : 85a11443-a781-4d79-9812-4bf983bbde48 and url https://s3.amazonaws.com/stochss-output-005305b4-7b38-43eb-b11a-0d23c0d4814a/output/85a11443-a781-4d79-9812-4bf983bbde48.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   329    0   329    0     0   2447      0 --:--:-- --:--:-- --:--:--  2455
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by briandrawert** [comment]
Celery.log showed this error:
```
<Error><Code>TooManyBuckets</Code>
<Message>You have attempted to create more buckets than allowed</Message>
<CurrentNumberOfBuckets>101</CurrentNumberOfBuckets>
<AllowedNumberOfBuckets>100</AllowedNumberOfBuckets>
```
