### ISSUE TITLE
FlexCloud: SSH key handling needs improvement 

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#386]
1.  Keys needs to be uploaded separately in a key upload box/tab/block. Also, a delete keys feature.
2.  If you upload a key with the same name get error.
3.  Key in the current active deployment are locked?

**Comment by dnath** [comment]
Partially done in d7f0c3f3ba3ce3e6381d548b4fb64c3603495414

No. 2 is not done.

**Comment by briandrawert** [comment]
This is fixed (including #2) in https://github.com/StochSS/stochss/pull/383
