### ISSUE TITLE
FlexCloud: "deploy" instead of "prepare"

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#387]
"Stop" or "Undeploy" for stopping the cluster

**Comment by dnath** [comment]
Done in f7ed7195053e176d4816c622e898f50f218e8e25

**Comment by ahellander** [comment]
It might be a good idea to use the same naming convention as in EC2/OS. (start, stop, and terminate.)

/Andreas
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On May 23, 2015, at 4:12 AM, dnath <notifications@github.com<mailto:notifications@github.com>> wrote:


Done in f7ed719<https://github.com/StochSS/stochss/commit/f7ed7195053e176d4816c622e898f50f218e8e25>

**Comment by dnath** [comment]
The reason I feel we should not use the words 'start' or 'terminate' as in Flex Cloud, you cannot start or terminate machines like in EC2. Machines should be already running with StochSS and software dependencies installed (via make_flex_vms.py) before clicking on 'Prepare'/'Deploy'. Similary, we won't kill the machines after we deregister the Flex Cloud Config.

'start'/'terminate' would be misleading in this context.

**Comment by briandrawert** [comment]
Now "Deploy" and "Stop" in #383
