### ISSUE TITLE
FlexCloud: Cost-analysis should be disabled

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#392]

**Comment by dnath** [comment]
disabled cost analysis for simulation & sensitivity jobs : fixed in cf7d06699fa58ee492f4e5eb47977a1a06946040

For spatial jobs, will do it when setting it up for #395

**Comment by dnath** [comment]
done in 4bfd63556b9535218187803870ed78d696a6cdef

**Comment by briandrawert** [comment]
Fixed in #383
