### ISSUE TITLE
Ensure that job data is deleted from S3 when EC2-cloud jobs are downloaded/deleted

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#398]

**Comment by briandrawert** [comment]
Fixed in 2719d33b26c3927374a2a39b1078995375a1d72e

**Comment by ahellander** [comment]
Should it really be deleted when downloaded?


Skickat från min Samsung Mobil.


-------- Originalmeddelande --------
Från: Brian Drawert
Datum:30-06-2015 16:17 (GMT+01:00)
Till: StochSS/stochss
Rubrik: Re: [stochss] Ensure that job data is deleted from S3 when EC2-cloud jobs are downloaded/deleted (#398)


Closed #398<https://github.com/StochSS/stochss/issues/398>.
