### ISSUE TITLE
FlexCloud: S3 replacement

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#399]
- Use SCP to get data
- When downloading data, delete from remote server
- When SSH keys are uploaded, rename to a unique name.  File should not be deletable (db entry can)
- Store SSH keyname, IPaddr of queue head in the job data

**Comment by dnath** [comment]
Done in 4bfd63556b9535218187803870ed78d696a6cdef

**Comment by briandrawert** [comment]
Fixed in #383
