### ISSUE TITLE
Weird error in logs on first StochSS load

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#404]
After I delete my datastore and open up StochSS I see this error in the logs. I'm checking this on the develop branch.

This seems like something that could be suppressed pretty easily?

```
ERROR    2015-05-27 17:21:40,816 connection.py:1130] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>c1865aa5-bbb4-4970-9a7e-9dacc1954ace</RequestID></Response>

In validate_Credentials
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/app/backend/agents/ec2_agent.py", line 403, in validate_credentials
    conn.get_all_instances()
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 574, in get_all_instances
    max_results=max_results)
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 655, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 1131, in get_list
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 401 Unauthorized
```

**Comment by dnath** [comment]
This is because it tries to connect with blank ec2 credentials.

I would want to turn this off as this gives an indication whether you have
invalid ec2 creds from the logs.

-Dev

On Wednesday, May 27, 2015, bbbales2 <notifications@github.com> wrote:

> Assigned #404 <https://github.com/StochSS/stochss/issues/404> to @dnath
> <https://github.com/dnath>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StochSS/stochss/issues/404#event-315181977>.
>


-- 
Sent from Gmail Mobile

**Comment by bbbales2** [comment]
I guess the question is it a caught or uncaught exception? If it's caught and handled I think it's fine and we can forget about this. Brian, what'dyou think?

**Comment by briandrawert** [comment]
I think it is caught, but the real bug here is that we see errors in the logs when there is no error.  I like Dev's idea have having an indication in the logs if the ec2 creds are valid, but we should remove the stack trace as to stop confusing ourselves.  Thoughts?

**Comment by briandrawert** [comment]
Consider this: https://github.com/StochSS/stochss/pull/406

Now I get this is stderr.log after I delete mydatastore:
```
INFO     2015-05-28 17:09:11,794 backendservice.py:445] validateCredentials: inside method with params : {'infrastructure': 'ec2', 'credentials': {'EC2_ACCESS_KEY': '', 'EC2_SECRET_KEY': ''}}
INFO     2015-05-28 17:09:11,795 backendservice.py:448] validateCredentials: exiting with result : <backend.infrastructure_manager.InfrastructureManager instance at 0x115ef8cb0>
ERROR    2015-05-28 17:09:12,140 connection.py:1129] 401 Unauthorized
ERROR    2015-05-28 17:09:12,140 connection.py:1130] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>63a2744d-d3fa-4a39-ae63-dad571932ed5</RequestID></Response>
ERROR    2015-05-28 17:09:12,143 ec2_agent.py:406] validate_credentials(): got EC2ResponseError
```

**Comment by bbbales2** [comment]
I'm a fan of the stack traces. Without them you usually don't have enough information to figure out what the problem really was.

In a larger perspective, I think all these errors need to be visible and digestible in the web interface too. Error logs from webserver, from computer nodes, from celery, from Javascript etc.

I'm happy closing this issue with or without the pull.

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/pull/406
