### ISSUE TITLE
FlexCloud: UI Issues

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#413]
Two issues in the UI:
   1. State: "unknown", can the user get some explanation what this might mean?
   2. after adding one flex server, clicking "Add machine" just creates more lines like the previous one. Seems like it is adding more forms, with the previous content filled and submitted.

**Comment by bbbales2** [comment]
What we did was copy the username/key from row to row. Is this what you meant with number 2?

**Comment by briandrawert** [comment]
2. is fixed, but 1. still need to be addressed.
