### ISSUE TITLE
Correct links on StochSS main page 

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#417]
Example Library is wrong.

"StochSS Users Google group" is wrong, and needs to open in a new window.

**Comment by bbbales2** [comment]
Example library and link open in new window should be fixed in https://github.com/StochSS/stochss/commit/4feb88a7d543997aecf0999ea446ff7747e2da62 and https://github.com/StochSS/stochss/commit/1f8517ae81f8f4567ceea19f08483b10709c7b6f

What StochSS Users group should we be pointing to?
