### ISSUE TITLE
Cloud Spatial jobs

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#424]
After running a spatial job in the cloud, but before downloading it, and error shows up on the spatial visualization page saying some stuff was inaccessible.

This error should be suppressed since the data isn't downloaded. Also the various spatial toolbars (animation/rotation one and the clipping one) should be hidden.

**Comment by dbjnbnrj** [comment]
Can you mention the error and the scenario so I can re-run and test the same/
Would trigerring a job with a lot of timepoints do?

**Comment by bbbales2** [comment]
Just run a spatial job in the cloud, and go to the output page. None of the visualization stuff should be visible until the user has clicked "Download Data from Cloud".

**Comment by bbbales2** [comment]
The solution should be hiding all the mesh controls until the page is loaded. Check how I show/hide things in app/static/js/spatial.js line 1194 (starts with "if ((data['resource'] == 'ec2-cloud'...")

That ajax request probably shouldn't fire at all if the data is stored in the cloud.

**Comment by dbjnbnrj** [comment]
Resolved and checked into caching branch

**Comment by bbbales2** [comment]
Fixed in #431.
