### ISSUE TITLE
FlexCloud: Build flex vm fails

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#427]
Updating instance...
Trial #5 of linux dependency installation failed!
Traceback (most recent call last):
  File "make_flex_vms.py", line 126, in make_flex_vm
    self.__try_install_dependencies()
  File "make_flex_vms.py", line 332, in __try_install_dependencies
    raise Exception("Linux Dependency Installation failed after {0} trials!".format(self.NUM_TRIALS))
Exception: Linux Dependency Installation failed after 5 trials!

**Comment by dnath** [comment]
Well, the script make_flex_vms.py tries to install the linux dependencies 5 times and then exits with failure. 

This is not a bug in the tool.

It usually means apt-get is not working properly --- cannot fetch stuff from repos or dependencies are broken. You should ssh into the machine and try running apt-get.

If you want more detailed error, just check the tool logs that are created in the same dir.

**Comment by ahellander** [comment]
Yeah, sorry, my bad. Wonder why apt-get failed though.

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jun 6, 2015, at 6:18 PM, dnath <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, the script make_flex_vms.py tries to install the linux dependencies 5 times and then exits with failure.

This is not a bug in the tool.

It usually means apt-get is not working properly --- cannot fetch stuff from repos or dependencies are broken. You should ssh into the machine and try running apt-get.

If you want more detailed error, just check the tool logs that are created in the same dir.
