### ISSUE TITLE
FlexCloud: make_flex_vms.py needs to report if the required ports are not open.

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#438]

**Comment by dnath** [comment]
fixed in c7abcc15eb6bff11fe0a59764df5151ebb2e2e7f

**Comment by dnath** [comment]
Above fix does not work

**Comment by dnath** [comment]
New fix: enable ports using ufw (iptables wrapper for ubuntu)

fixed in 0184fd31b24dd87819f67dac7e45d0127f147291

**Comment by briandrawert** [comment]
I checked this by running it against a VM with a security group that did not have all the ports open.  It never reported any errors

**Comment by dnath** [comment]
fixed in https://github.com/StochSS/stochss/pull/462

**Comment by briandrawert** [comment]
Fixed in #383
