### ISSUE TITLE
Stochoptim job not reporting finished

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#443]
Stochoptim job appears to be finished (via stdout) but not showing finished

**Comment by bbbales2** [comment]
status.py doesn't seem to be aware of difference in ec2-cloud and flex-cloud

**Comment by dnath** [comment]
fixed in cba16ed64416486615e0175d27db10969090a76a

**Comment by briandrawert** [comment]
Still doesn't work

**Comment by briandrawert** [comment]
It now reports finished.

**Comment by briandrawert** [comment]
Fixed in https://github.com/StochSS/stochss/pull/460
