### ISSUE TITLE
Flex Cloud invalid nodes

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#446]
If you configure invalid nodes on the Flex Cloud page and launch them, the process never fails. It just keeps trying to launch the nodes

**Comment by briandrawert** [comment]
Also the state is "Unknown", should be "inaccessible" (not "unaccessible")

**Comment by briandrawert** [comment]
Also, the main cloud computer page, show that neither EC2 or Flex is select, however, when you click on Flex, it shows that flex is "deploy"ed
