### ISSUE TITLE
Jobs not deleting properly

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#461]
Stochkit and spatial jobs do not support flex cloud.

Sensitivity and stochoptim appears to not delete any data at all.

**Comment by dnath** [comment]
fixed in https://github.com/StochSS/stochss/pull/463

**Comment by briandrawert** [comment]
Sensitivity jobs do not get deleted.

**Comment by briandrawert** [comment]
Parameter estimation jobs do not get deleted.  In addition, these jobs have the same tar files in both "~/output/" and "~/stochss/app/backend/tmp/flex/output".

**Comment by briandrawert** [comment]
Sensitivity fixed in 286cd793eb6cc8f5f1a74eeb1caa4f67be116174

**Comment by briandrawert** [comment]
Stochoptim fixed in a04469b5074953767c60554cea5420ed2d13d5b8 and 2b7ec4dade1d39764454d59ffa787a9faa54d027
