### ISSUE TITLE
Launching invalid nodes in Flex Cloud

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#464]
Requesting the launch of a non-existant flex cloud node takes a long time to fail (and it never fails, it just runs a node in an unaccessible state)

Needs to be fixed in https://github.com/StochSS/stochss/pull/383

**Comment by bbbales2** [comment]
Just to be clear, this should fail.

**Comment by bbbales2** [comment]
So I've done some sleuthing on this.

stochssapp.py:147 update_flex_cloud_machine_info_from_db(self):

This is the function that is responsible for getting info from the db and writing it to the user. If it can't find info for a machine, it just says it is inaccessible.

You see in the loops it's using the ip information to transfer information from the updated status (all_vms, 143) into the cached db (flex_cloud_machine_info).

It seems though like that ip information isn't always there.

The only place I see the ip information being assigned is in VMStateModel.update_ips. I don't think this gets called properly in the case that the machines don't exist.

I think the solution is to re-engineer the flex_cloud_machine_info to store other identifier information. I don't know what all the options are. It seems the only thing that is populated in all_vms at that point is reservation_id, and I don't know what that means. There is also an ins_id variable but it isn't populated either.

----

Also, in vm_state_model.py:410 synchronize, I bet there is a bug in how the state assignment is done there.

I don't really know but the transitions between the states defined at the top of vm_state_model shouldn't be free. You know? Like, you don't go from Terminated to Running. I'm not sure that transition should happen, but it can.

Unknown shouldn't overwrite Terminated, etc.

**Comment by bbbales2** [comment]
infrastructure_manager.py:24 InfrastructureManager claims to support blocking and non-blocking modes. The blocking mode does not work

**Comment by bbbales2** [comment]
I think it's backend_handler.py:282 __poll_instance_status that calls vm_state_model.py:305 update_ips to set the ips in the VMStateModel objects so that the flex_cloud_info can map information from the VMStateModel to the UI.

In any state other than 'UNPREPARED,' the updateips never makes the ip assignments. If this logic is changed so that the assignments are made, then VMStateModel fails because it doesn't have the 'ins_id' information to map the ips to VMStateModels.

**Comment by bbbales2** [comment]
Alright, so the states are communicated back to the UI correctly now: https://github.com/StochSS/stochss/commit/cb9f26f2fc40d03d6392e2ab5f2815827c373247

However, the states don't really make sense. I sometimes see terminated, creating, inaccessible...

**Comment by briandrawert** [comment]
I think this is fixed in d397e3a75ca136ff2e29c5ceb951b8afba613383

**Comment by bbbales2** [comment]
This appears to be fixed.
