### ISSUE TITLE
Flex Cloud data can become unaccessible

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#467]
If a user runs jobs in a flex cloud, turns off the cloud, deletes the keys to that cloud, and then tries to access any undownloaded data, they will get unexpected errors.

They should get controlled errors instead.

**Comment by briandrawert** [comment]
Addressed in 383876d3e946e258e633442ad0f0e59b4f798f79

**Comment by bbbales2** [comment]
Checked this. I see the 'Inaccessible' message when I turn off a Flex Cloud instance while data is still in the cloud. Seems good to me.
