### ISSUE TITLE
Inaccessible cloud jobs not deleting

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#474]
Inaccessible cloud jobs not deletable

**Comment by bbbales2** [comment]
This commit addresses the issue in refactor: https://github.com/StochSS/stochss/commit/4dacb84372a0db2130bab85472e4aeed8601eb2b

It assumes that delete should continue delete from the local db regardless of what the Cloud says. It seems like there might be a better way to handle the difference in cloud is missing (inaccessible jobs) or cloud just accidentally threw a different error.

**Comment by bbbales2** [comment]
Revert the commit if you don't like it.

**Comment by briandrawert** [comment]
Duplicate of #480?

**Comment by bbbales2** [comment]
Verified fixed (yes duplicate)
