### ISSUE TITLE
Stochoptim Jobs do not re-task queue back to the main queue

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#480]
This mean that after you run a stochoptim job, your cloud resource are always unavailable.  poll_task.py is supposed to do this, but it does not work all the time.

**Comment by briandrawert** [comment]
This is addressed in 4d5cb1dbf69c19edd54875c699171cc9fa9c4a98

**Comment by bbbales2** [comment]
Confirmed fixed
