### ISSUE TITLE
Add Hes1 spatial model from CSHL tutorial to public models

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#484]
Since it is a fun model.

**Comment by briandrawert** [comment]
[Hes1_C1Jb8j.zip](https://github.com/StochSS/stochss/files/152036/Hes1_C1Jb8j.zip)

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/commit/a215ccfb1561881930fbe1b8b42f8c99348ff5c6

**Comment by ahellander** [comment]
ok.
