### ISSUE TITLE
Job status firs shows Failed then Completed 

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#485]
I ran some well mixed stochastic models locally. First they show Failed, and the stdout, then shortly after flip to completed and displays the correct result. Too fast polling somewhere?

**Comment by briandrawert** [comment]
What branch was this in?

**Comment by ahellander** [comment]
refactor
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jun 26, 2015, at 12:42 AM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:


What branch was this in?

**Comment by bbbales2** [comment]
I've not been able to reproduce this. Can you Andreas?

If not then close.

**Comment by ahellander** [comment]
I can't reproduce it in most recent develop. Whatever it was, it is gone.
