### ISSUE TITLE
EC2 Instances sometimes won't launch

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#495]
1. Click "Launch Nodes" on EC2 page
2. Page goes into launching mode
3. Page eventually goes back to like it was before pressing buttons, no errors, no nodes

The weird thing is the logs seem to show an instance launched and 'ec2-describe-instances' shows a launched instance.

I removed a line of code that possibly changed this behavior but the bug is rather intermittent and I'm not sure it's solved yet https://github.com/StochSS/stochss/commit/228b0f3572753ba8766608d0627909e7f65fa6bc

**Comment by briandrawert** [comment]
Can not reproduce.
