### ISSUE TITLE
FlexCloud UI page does not behave well with window rescaling

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#497]
![screen shot 2015-07-01 at 1 43 06 pm](https://cloud.githubusercontent.com/assets/2364390/8453676/27343e0e-1ff7-11e5-8c72-cd3c826d2db5.png)

**Comment by bbbales2** [comment]
Fixed: https://github.com/StochSS/stochss/commit/29144058aaed9c975b018024d81f120e976a2253

**Comment by briandrawert** [comment]
Fixed in develop
