### ISSUE TITLE
ModelEditor, Reaction formula in clear text is excessively large.

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#498]
![screen shot 2015-07-01 at 1 46 45 pm](https://cloud.githubusercontent.com/assets/2364390/8453726/b7463984-1ff7-11e5-8f5d-2e89307840da.png)

**Comment by ahellander** [comment]
Also, it does not rescale gracefully either.

**Comment by bbbales2** [comment]
I can make it smaller, but if a_n_d_r_e_a_s_h_e_l_l_a_n_d_e_r keeps using long variable names, there will always be a breaking point. At least at the scale of your screenshot, it looks pretty graceful to me. If you get much smaller it will all fall apart though.

**Comment by bbbales2** [comment]
I made the font smaller: https://github.com/StochSS/stochss/commit/98ce500206ee5c20a73a62631e2ebc5756fdd565
