### ISSUE TITLE
Spatial Viz: Make concentration default, show warning when switching to population. 

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#499]
The warning should say "Warning: Population plots of unstructured meshes can be misleading"

-------------------------------  
Previous description
-------------------------------  

You always have to plot with a scaling of voxel size, if not, the picture will be misleading on an unstructured mesh since the volumes are variable. You should remove the current option to plot only molecules and just go with number density

#molecules/subvolume_size 

Everywhere.

To give the user an impression of where particles are, it is better to do a particle-style plot (now available in pyurdme, see 'display_particles' method in URDMEResult) although this also has a risk of being misleading, but in a different (and more easy to explain ) way.

**Comment by bbbales2** [comment]
I agree with what you said, but I don't consider myself the expert. Brian?

**Comment by briandrawert** [comment]
I agree with Andreas, that it is misleading.  But I also think that there are times I want to know the population, not the concentration.  I think that we should have concentration be the default, and population be an option (as it is now)

**Comment by bbbales2** [comment]
Yeah now I agree with Brian. For debugging purposes, the concentration is the hard one to work with (cause you need to know the volume to know how many things are there!).

**Comment by ahellander** [comment]
I am fine with knowing the population somehow, but not in this type of plot on unstructured meshes. There is a risk that things look like clustering when it is close to uniform etc. It can lead to wrong biological conclusions. I will not budge on this one :-)
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jul 1, 2015, at 7:14 PM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah now I agree with Brian. For debugging purposes, the concentration is the hard one to work with (cause you need to know the volume to know how many things are there!).

**Comment by briandrawert** [comment]
You want to remove the capability from StochSS to plot population?  I disagree.  Not make it the default, and/or show a warning. That I can agree with, but to assume that no user will ever want that feature is not ok.  I know that I want that feature.  I use this exact plot, with only population shown, on unstructured meshes in our research.

**Comment by ahellander** [comment]
The plot is wrong. That is why i want to remove it.


Skickat från min Samsung Mobil.


-------- Originalmeddelande --------
Från: Brian Drawert
Datum:01-07-2015 19:43 (GMT+01:00)
Till: StochSS/stochss
Kopia: Andreas Hellander
Rubrik: Re: [stochss] Spatial Viz: Remove population plot style. (#499)


You want to remove the capability from StochSS to plot population? I disagree. Not make it the default, and/or show a warning. That I can agree with, but to assume that no user will ever want that feature is not ok. I know that I want that feature. I use this exact plot, with only population shown, on unstructured meshes in our research.

**Comment by briandrawert** [comment]
Not wrong, but misleading.  Updated title and comment to reflect result of off-line discussion.

**Comment by bbbales2** [comment]
Fixed in: https://github.com/StochSS/stochss/commit/d997edbe3becf6b1726a0b8f86558e0a46bdbc5e

Check the message see if it's appropriate

**Comment by briandrawert** [comment]
I changed message to "Warning: the population plot is not normalized to volume. Interpretation of this plot can be misleading" in a721e1bc18fc3fd81e485d5a2c52215cd9bc9e81

**Comment by briandrawert** [comment]
Andreas' suggestion: we can put a "?" with a modal popup (like on the ec2 cloud page) with a longer explanation.

**Comment by bbbales2** [comment]
Nah, I don't want to do that. I'm vetoing your idea Andreas.

Those things are annoying to code and maintain. I also personally do not like using them. If information needs to be on a site, why hide it in a little box?

I don't see any reason it needs to be longer either. Just as long as the user knows it's questionable, I think we've done enough. I don't want to try to delve into why they're looking at the plot and why they may or may not be wrong to do so.

**Comment by ahellander** [comment]
Whatever. I still have reservations, but mainly in having this feature at all. Hopefully if the google the warning, they will end up in this discussion thread. Sure, go ahead with the warning message.

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jul 7, 2015, at 8:41 PM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Nah, I don't want to do that. I'm vetoing your idea Andreas.

Those things are annoying to code and maintain. I also personally do not like using them. If information needs to be on a site, why hide it in a little box?

I don't see any reason it needs to be longer either. Just as long as the user knows it's questionable, I think we've done enough. I don't want to try to delve into why they're looking at the plot and why they may or may not be wrong to do so.

**Comment by briandrawert** [comment]
Closing issue
