### ISSUE TITLE
Spatial Viz: Changing trajectory ID does not update the plot

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#500]
Alternatively, all trajectories are the same.

**Comment by bbbales2** [comment]
Wow, good find.

**Comment by bbbales2** [comment]
You'll need to clear your datastore: https://github.com/StochSS/stochss/commit/530d21535c51ba12f2f05e5f423a9a4a2c43e0b8

**Comment by briandrawert** [comment]
Fixed in develop
