### ISSUE TITLE
Spatial Viz: Redundant checkboxes

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#501]
Is not the checkboxes to activate clipping in the different coordinates redundant, since the slider will just not clip if at its leftmost position?
![screen shot 2015-07-01 at 2 42 41 pm](https://cloud.githubusercontent.com/assets/2364390/8454665/971f9c2e-1fff-11e5-9c0b-ed76f7ff65e6.png)

**Comment by bbbales2** [comment]
I see what you're saying, but I don't agree with the change.

I don't think I've ever seen an interface like that and in something complicated and technical like this I'd rather be more explicit with things.

**Comment by briandrawert** [comment]
I had a similar comment, but didn't get a clear enough idea of what it should be.  So I agree in principle.  Maybe there should be just one button "activate clipping" that enables the whole box.  I am open to other ideas, but I think it is too much to have 3 checkboxes, and zero is too few.

**Comment by bbbales2** [comment]
I'm not into overthinking this bit of the GUI. It's as clear as it gets now. Removing two of those six checkboxes isn't gonna fundamentally change anything.

**Comment by briandrawert** [comment]
I am going to push this to 1.7, we can think about it again later.

**Comment by bbbales2** [comment]
We decided to keep 3 buttons.
