### ISSUE TITLE
Hide Cost analysis on local jobs

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#502]
Why show it just to say it is not available? For consistency?

**Comment by briandrawert** [comment]
Agreed, let's remove the UI elements on non-EC2 jobs

**Comment by bbbales2** [comment]
Fixed in: https://github.com/StochSS/stochss/commit/afdc5e3d9525b2ab7168fe51bbea5b7fa39e1ad8 and https://github.com/StochSS/stochss/commit/5bfcc038a422028c707f5fda3b5c1e510a372117

**Comment by briandrawert** [comment]
Fixed in develop
