### ISSUE TITLE
FlexCloud make_flex_vm.py failed on first run

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#503]
In SMOG, with security group stochss_flex_cloud, I got this first time executing the script
achine with ip: 130.238.29.100 reachable.
==================================================
Trying to enable ports = [22, 5672, 6379, 11211, 55672, 80, 443, 3306]...
Traceback (most recent call last):
  File "make_flex_vms.py", line 129, in make_flex_vm
    self.__enable_network_ports()
  File "make_flex_vms.py", line 369, in __enable_network_ports
    self.__run_remote_command(command=command, log_header=header)
  File "make_flex_vms.py", line 663, in __run_remote_command
    shell_cmd.run(timeout=timeout, silent=silent)
  File "make_flex_vms.py", line 99, in run
    raise ShellCommandException("return code = {0}".format(self.process.returncode))
ShellCommandException: return code = 255
Done in 50.5179820061 seconds
Completed all machines in 50.5181558132 seconds.

But next time I tried, it worked.

**Comment by briandrawert** [comment]
Looking around, I found: http://stackoverflow.com/questions/14885748/ssh-script-returns-255-error
Which indicates that there was an authentication error.  Since there was some issues with ssh (discussed via email), I am going to close this.
