### ISSUE TITLE
Additional Spatial plots and plot info

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#504]
For Spatial models, either counts or a plot of the sum of each species in each subdomains.  We could implemented this as counts shown on the plot page, or time series plots.

**Comment by ahellander** [comment]
This could be a great time to try that Matplotlib/JavaScript integration project that Ben found.

**Comment by briandrawert** [comment]
http://mpld3.github.io/

**Comment by briandrawert** [comment]
This is fixed by the notebook integration in #633
