### ISSUE TITLE
Flex Cloud SSH key should not select a default key

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#505]
When I go to the flex cloud page for the first time.  Then I upload 2 keys. When I start to fill out the flex cloud machine info, it has already selected a key for me, the first by alpha sorting.  It should say "Select a key" instead.

**Comment by bbbales2** [comment]
Should be fixed in https://github.com/StochSS/stochss/commit/49bf49d60a4ab82cefa9ee807135ef7907a75f67

**Comment by briandrawert** [comment]
Fixed in develop
