### ISSUE TITLE
Flex Cloud, state of machine is not reported accurately for multiple machines

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#506]
See screen shot.  I have 2 machine, one is running, one is unprepared, but the UI mixes up which is which.

![ss](https://cloud.githubusercontent.com/assets/1413538/8486561/43d7adc0-20ba-11e5-8521-87feed80ec88.png)

**Comment by briandrawert** [comment]
![ss](https://cloud.githubusercontent.com/assets/1413538/8486673/1e7bca10-20bb-11e5-82e4-97938089f986.png)

**Comment by briandrawert** [comment]
Also, Flex cloud with multiple machine does not seem to work at all.

**Comment by ahellander** [comment]
I think this was my problem yesterday as well (main thread with Brian), I was always trying to deploy multiple VMs. Sometimes one started, but never more than one.

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jul 2, 2015, at 10:07 PM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, Flex cloud with multiple machine does not seem to work at all.

**Comment by briandrawert** [comment]
Fixed with 6a29314d697d7d2ad517e11ce0491ce1898495d2

**Comment by bbbales2** [comment]
This works
