### ISSUE TITLE
Errors with UFC versions

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#507]
When Tie launched StochSS (totally fresh install) his public models weren't loading.

We looked in the logs and found:
Exception: Incompatible swig versions detected. UFC swig version is not the same as extension module swig version: '2.0.11' != '2.0.4'

(this was happening in the pyurdme code that builds the public library)

We found the solution (http://fenicsproject.org/qa/3348/how-do-i-fix-incompatible-swig-versions-detected-error) was to run the command 'instant-clean.' (we tried uninstall and reinstalling packages but that didn't work)

Apparently instant is a Fenics module and needs cleaned in some way: https://bitbucket.org/fenics-project/instant ?

Is it too radical to propose we do instant-clean when we launch the application? I don't know what effect this would have on other Fenics applications running at the same time, but I think it'd fix the problem Tie saw.

**Comment by ahellander** [comment]
instant_clean is for the JIT compiler in Fenics, and cleans the cache. It should be saft to do an instant_clean on startup. Only effect should be that it needs to JIT again.




-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jul 3, 2015, at 1:14 AM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


When Tie launched StochSS (totally fresh install) his public models weren't loading.

We looked in the logs and found:
Exception: Incompatible swig versions detected. UFC swig version is not the same as extension module swig version: '2.0.11' != '2.0.4'

(this was happening in the pyurdme code that builds the public library)

We found the solution (http://fenicsproject.org/qa/3348/how-do-i-fix-incompatible-swig-versions-detected-error) was to run the command 'instant-clean.' (we tried uninstall and reinstalling packages but that didn't work)

Apparently instant is a Fenics module and needs cleaned in some way: https://bitbucket.org/fenics-project/instant ?

Is it too radical to propose we do instant-clean when we launch the application? I don't know what effect this would have on other Fenics applications running at the same time, but I think it'd fix the problem Tie saw.

**Comment by briandrawert** [comment]
I agree. We can run 'instant-clean' at startup and it shouldn't have any negative consequences.

**Comment by briandrawert** [comment]
Mac startup script modified here: 25245ea89bd0745e00c76f251b594f3913a741e0

**Comment by bbbales2** [comment]
Ubuntu and Embedded Mac scripts fixed here https://github.com/StochSS/stochss/commit/926d1f465aa9a0e902f2473ada6368f69032995d and here https://github.com/StochSS/stochss/commit/99eb0167d024ad0d663c6a7c4434b8752c51432c.

I did not test the embedded Mac script.

**Comment by briandrawert** [comment]
Fixed in develop
