### ISSUE TITLE
Different spatial trajectories all have the same initial conditions

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#508]
I noticed this when I was testing the different trajectories in the spatial output. They all have the same initial condition distributions.

Is this a bug? Is this a feature? Thoughts?

**Comment by ahellander** [comment]
This is something we have wondered a lot about. But I think we decided we should have the same initial condition in an ensemble of trajectories. The variability comes from the intrinsic noise. But I can also see why one would want a random scattering to be different in each invocation of the solver. I think the solution then is that you have to create a new solver instance. This would, and is kind of logical, but hurts performance. So in short, there are mechanisms in pyurdme to do both, and what you get depends on how you invoke the solvers (iterate on one solver or create new sovers). Which one do we want in StochSS, I don’t know.



-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Jul 3, 2015, at 11:29 PM, bbbales2 <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed this when I was testing the different trajectories in the spatial output. They all have the same initial condition distributions.

Is this a bug? Is this a feature? Thoughts?

**Comment by briandrawert** [comment]
I am going to push this issue till the next release.

**Comment by ahellander** [comment]
If I had to choose one, I would choose the existing solution. Ofc, having both would be better, but I agree, that can wait.

**Comment by bbbales2** [comment]
Answered!
