### ISSUE TITLE
Stopping Cloud Spatial jobs doesn't work

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#509]
I ran a long cylinder demo job in the flex cloud (t = 10000 or so). Deleting a running job did not kill the process on the server.

**Comment by briandrawert** [comment]
Fixed in e8d62b2918875a1b55572d80a6e3dae703dd6940

**Comment by briandrawert** [comment]
EC2 AMI updated in c507937ef37725f76749aec747402639fbe7c1f6
When testing flex-cloud, but sure to update the code on your instance.

**Comment by bbbales2** [comment]
Checked in EC2 and Flex
