### ISSUE TITLE
SBML imported models 'mass action' discrepancy.

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#510]
Bernie reported that they are listed as "Non-mass action" in the Model Editor, but in the Simulation Editor these models were then listed as "Mass action".

**Comment by bbbales2** [comment]
Confirmed!

So on the simulate page, I don't have enough information to say whether or not a model is mass-action or not (would have to iterate through all its reactions to get that).

Fix here: https://github.com/StochSS/stochss/commit/2269e5ed3161086719501820785fad921483dc1e

I could also iterate through the models and get this mass-action not mass-action info but I don't think this is make or break.

**Comment by briandrawert** [comment]
Looks good to me.
