### ISSUE TITLE
Parameter Estimation page should prohibit non-mass action models

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#511]
Currently, the first page of the parameter estimation allows any non-spatial population model to be simulated.  This results in errors.  The first page should check if the model is non-mass action, and prohibit it's use.

**Comment by bbbales2** [comment]
This should be fixed here: https://github.com/StochSS/stochss/commit/14fc5f3d334db1b8f05827c3d8cd9165014dd7f3

**Comment by briandrawert** [comment]
Fixed in develop
