### ISSUE TITLE
FlexCloud: if the ports are not open, the user should see that error message quickly

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#512]

**Comment by briandrawert** [comment]
This should be addressed in 8b40e27460f002924922dae47237430b45de8c11
For testing: be sure the flex cloud workers have the latest code and have restarted their apache webserver.

**Comment by briandrawert** [comment]
More fixes here 8b4b1dbae4617fe17d0ee1fe56794afa0c4983a2

**Comment by bbbales2** [comment]
I tested all job types (I think) with this. The features seem to work.

I stopped the ec2 nodes via command line while the StochSS Flex cloud was configured, and correctly saw 'inaccessible' status on the status page for jobs not downloaded. This was fast. I think this is the desired behavior?
