### ISSUE TITLE
Model 28

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#518]
Biomodel 28 imports successfully but will have negative propensity functions (here it is https://www.ebi.ac.uk/biomodels-main/BIOMD0000000028).

This runs in StochkitODE but should fail in Stochkit.

We should verify that the error gets reported correctly back to the UI.

**Comment by ahellander** [comment]
Do you mean that the model is constructed so that it has negative propensities, or that it gets that cause to some bug? In the former case, there is something wrong with the model.
