### ISSUE TITLE
Stochastic Simulation Status Wrong

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#529]
Set parameter k2 to "sin(k1 / 100)" in the birthdeath example model

The output page shows that the job failed but on the status page it shows "Finished". This is running as a Stochastic model.

**Comment by bbbales2** [comment]
This is happening because even though StochKit fails, it returns a zero.

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/commit/2dadfb76f900a7b27cd1c835aa602d2e782c45ea

**Comment by briandrawert** [comment]
Error show on page correctly.
