### ISSUE TITLE
StochSS Volume Rendering Visualization Bugs

### ISSUE THREAD

**Issue by dbjnbnrj** [StochSS/stochss#535]
List of Bugs left behind in the volume branch -

- Spatial rendering of Spherical mesh not working
- Artifact appears for volume rendered cylindrical mesh
- Mesh color to be updated from red to other color
- Animation fails to render mesh completely at certain time periods (mesh appears as a dot on screen)
- Improve performance for volume rendered mesh. 
- Currently rendering a 128 * 128 mesh, this has to improve in resolution to 1024 * 1024

**Comment by bbbales2** [comment]
- -Spatial rendering of Spherical mesh not working-
- Artifact appears for volume rendered cylindrical mesh
- Mesh color to be updated from red to other color
- Animation fails to render mesh completely at certain time periods (mesh appears as a dot on screen)
- Improve performance for volume rendered mesh. 
- Currently rendering a 128 * 128 mesh, this has to improve in resolution to 1024 * 1024
