### ISSUE TITLE
mysql-connector not installing

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#536]
The pip repository does not have the correct link for mysql-connector, thus the installation of StochSS fails currently.  The solution is to use this command:

sudo pip install http://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.0.4.zip#md5=3df394d89300db95163f17c843ef49df

Hopefully, the repository maintainers will fix this soon.

**Comment by aviral26** [comment]
This is how we install mysql-connector on the image now

**Comment by ahellander** [comment]
This worked for my on Ubuntu: 
apt-get install python-mysql.connector

**Comment by bbbales2** [comment]
Addressed in https://github.com/StochSS/stochss/pull/546

**Comment by bbbales2** [comment]
Fixed in https://github.com/StochSS/stochss/commit/e93960242637c70c1aae3d81a4efd13e2789eeab
