### ISSUE TITLE
Shortcut to simulation from the Model Editor page. 

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#555]
It would be great if there were actions on the Model editor page to directly run the solvers (with the last known settings) without having to switch to the Simulate tabs. This will save time when one is fiddling around with model parameters and re-running the same solver for each new set.

**Comment by briandrawert** [comment]
partially addressed in b4496cad474c4489fd6920549ee2e420096787d9

**Comment by briandrawert** [comment]
Simulation page settings are now persistent (in 5a327e3f19b3cb7b19464ddf98712b62b45c8f77)
