### ISSUE TITLE
stochoptimpage does not detect that there are no running cloud resources

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#557]
instead, you get the "green" status message "Running job in the cloud..." and it stays on the simulate page for ever (never redirects to Job Status)

**Comment by briandrawert** [comment]
I am getting the correct error when I test this in the develop branch now.  Andreas, Ben, can you confirm?

**Comment by bbbales2** [comment]
It was a problem if you hadn't selected Trajectory or Initial Data files. Fixed in https://github.com/StochSS/stochss/commit/c98e06a7fd2abd54ba1ec96ef334d55dc2f80454
