### ISSUE TITLE
Remodel ODE solver simulation page?

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#558]
Having use the ODE solver to try to model things it is very annoying to have to launch simulation jobs for runs that complete in the blink-of-an-eye. Instead, what if simulations were controlled on the visualization page and we imported the parameter list from the model editor for a particular model. We could then try to have sliders for the parameters, and then run simulations more or less interactively, updating the plots in near real-time. That would be so much nicer that what we have today.

**Comment by bbbales2** [comment]
I like this idea. Except for the sliders.

Ben
