### ISSUE TITLE
Model editor lets me input invalid initial conditions 

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#570]
in a concentration model, in mu case 1/(1e-15*6.022e23). 

The simulation page chokes on it though and fails gracefully with an informative error message. It would be better if the model editor told me directly that it will not work.

**Comment by bbbales2** [comment]
How's that an invalid initial condition?

**Comment by ahellander** [comment]
Ask the ODE simulation page… it said only single numeric values are allowed. I thought we parsed them, maybe that is only true for the stochastic models.

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Mar 2, 2016, at 10:48 PM, Ben Bales <notifications@github.com<mailto:notifications@github.com>> wrote:


How's that an invalid initial condition?
