### ISSUE TITLE
Linux README for stochss-laucher is incomplete

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#581]
- Needs a short description of what the launch program is and what it does
- lauchscript may not be executable, need to provide instructions for that (maybe "sudo bash ./launchContainer1.7.sh")
- Needs to specify that "docker" is a dependency, with instructions on how to install it (maybe just a link)

**Comment by bbbales2** [comment]
We should add to the readme that Docker doesn't work with Ubuntu 12.04

**Comment by briandrawert** [comment]
Fixed in 56f71cf2a500e63e249634e150a4456e60fc5892
