### ISSUE TITLE
Starting a negative number of instances

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#584]
It should not be possible to enter  a negative number of instances to start on the cloud advanced tab. Currently, the "up/down" arrows will let you do that.

**Comment by bbbales2** [comment]
Does it give a coherent error when you try launch them though?

The html5 number boxes can misbehave. If a reasonable error comes back when you try to launch I think it's okay.

**Comment by ahellander** [comment]
If one sets a type to -1, it seems to cowardly refuse to start any nodes, but give no error message.

**Comment by briandrawert** [comment]
I am going to push this to 1.8, since it doesn't actually make an error.  A warning message would be nice.
