### ISSUE TITLE
Changing from concentration to population plot does not change the scale of the colorbar

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#586]
For solid-type visualization of spatial realizations, changing units to populations still shows concentration values on the color bar on the right-hand side.

**Comment by briandrawert** [comment]
Fixed in eb5ec9adf8605619634bb66b61dc573438f92ab3

**Comment by briandrawert** [comment]
fixed in 80677eec6a20c78fc3168cf63ea76d85f07c2f5d
