### ISSUE TITLE
Docker uninstall for Linux and Windows

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#588]
Is there an Docker uninstall script for Linux?

**Comment by briandrawert** [comment]
Good catch!

**Comment by aviral26** [comment]
Maybe we don't need one? 
To uninstall on Linux, we just need to run `docker rm stochsscontainer1_7` to stop the container and `docker rmi aviralcse/stochss-initial` to delete the image.

**Comment by bbbales2** [comment]
That makes sense. Adding directions to the Readme.md is good enough for me. I just had to figure that out myself was the issue.

**Comment by briandrawert** [comment]
This is true for the windows readme as well

**Comment by aviral26** [comment]
Fixes

Windows : 38a76a772eb570881c0d11ae35b106ef289281eb 
Linux : 34a82249b3e61c8a63cec46ec2609e04b74e398d

**Comment by briandrawert** [comment]
Looks good!
