### ISSUE TITLE
Model Editor page take a long time to load

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#599]
In StochSS 1.7, every time I go to the model editor page, I have to reload the page 3-5 times before it will show anything except "loading...".  Waiting does not usually solve the problem (waited 30 minutes for it to load today).

**Comment by bbbales2** [comment]
I'm going to get rid of the Hes1 model and try it. That's the only thing that changed in 1.7.1? Anyone remember anything else?

**Comment by bbbales2** [comment]
It's probably something like the mesh is large and it's being handled by inefficient code in the JS.

**Comment by briandrawert** [comment]
Why is the mesh being loaded, when I have not even selected a model yet?

**Comment by bbbales2** [comment]
I dunno if it is, just a hypothesis. Why should a 1 meg mesh load slow down your computer even if it was being loaded?

**Comment by briandrawert** [comment]
Can we make it so that we only load models, when they are selected?  We need to test this with 100 models in the model editor and see if it works.

**Comment by ahellander** [comment]
Where are we on this one? Extending the timeout, sure, but better stil if we find a way to improve the loading time. We need to be able to have spatial models with big meshes in the editor.
