### ISSUE TITLE
Domain clipping checkboxes are a tiny bit annoying

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#602]
It is a little bit annoying to have to first check a box to slice the x-axis and the move the slider. Why can't I just slide the slider?

**Comment by briandrawert** [comment]
I feel the opposite.  I like that you have to enable the clipping. Plus, I often set the clipping positions, then enable/disable the x/y/z directions to show different angles.  Without the enable/disable, I can not do that.

**Comment by briandrawert** [comment]
What if we enable the clipping when that slider is moved?

**Comment by ahellander** [comment]
That would be great. Then having it to the left-most (zero) point would be no clipping. I think it would be logical. If it is possible. It would reduce the numbers of controls.

/Andreas
-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Apr 11, 2016, at 11:29 PM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:


What if we enable the clipping when that slider is moved?
