### ISSUE TITLE
Model editor mesh summary could be an accordion dropdown

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#603]
It is important information but I feel that the first thing on the page should be the display of the mesh. We could show the summary of dimensions, volumes etc. underneath the mesh, possibly by clicking a link "show dimensions and volumes"

**Comment by briandrawert** [comment]
In addition, the mesh preview can be a problem is the mesh is very large.  This causes the browser to slow down, making the model editor page very slow to respond.  It would be nice if the mesh was only shown on request.

**Comment by ahellander** [comment]
Partially implemeted in the saas branch. We need to improve so it can be both shown and hidden.
