### ISSUE TITLE
A new spatial model has no mesh

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#606]
When creating a new spatial model the cylinder demo mesh is chosen by default, but when simulating is says that no mesh is in the model.
![screen shot 2016-05-30 at 1 40 46 pm](https://cloud.githubusercontent.com/assets/2364390/15648676/64ff6098-266c-11e6-99b0-2bea51c76c07.png)

**Comment by briandrawert** [comment]
Fixed by bf6c7b5399c134e35ed8cd0cfb7541d9bf61e20b
