### ISSUE TITLE
The content of the datastore not persisted if the application is not terminated normally. 

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#61]
If the app is terminated using Ctrl-C in the terminal (or closes the terminal normally) the content of the datastore is flushed and persisted until the next launch, but if the application "crashes", or if the user force quits it, the new content in the app is lost.

**Comment by bbbales2** [comment]
This is too hard to address. Most database are going to have similar issues. It also hasn't been an issue in practice.
