### ISSUE TITLE
Parameter Sweep issues

### ISSUE THREAD

**Issue by briandrawert** [StochSS/stochss#647]
- Switching between "one parameter" and "two parameter resets the value of min and max
- Visualization page (one parameter), y-axis should have label "Value of Reducer metric"
- Visualization page (one parameter), should be able to hide/show different reducers (like we can with species on the simulation viz page)

**Comment by briandrawert** [comment]
For 2D sweeps, the x-axis letters overlap
![ss_tmp1](https://cloud.githubusercontent.com/assets/1413538/18077218/e894dab4-6e38-11e6-912c-a5f537ae5160.png)

**Comment by briandrawert** [comment]
For 1D sweeps, the x-axis is all zeros for some reason:
![ss_temp2](https://cloud.githubusercontent.com/assets/1413538/18077433/71081d2e-6e3a-11e6-9dea-e2ae4f488e99.png)

**Comment by briandrawert** [comment]
When the parameters are set to "log scale", the x-axis is still set to a linear scale.

**Comment by bbbales2** [comment]
* More info on results page (what parameters were swept over)
* Mapper that does final time point
* Make mapper names verbose (maximum over time series, maximum over ensembles, etc.)
* Change title to Postprocessing
* Results page needs to know if it was run as deterministic or stochastic or spatial

**Comment by briandrawert** [comment]
For a 2D sweep, I choose 3 pts for the x-axis and 4 pts for the y-axis.  Then the plotting looks very weird:
![ss_tmp1](https://cloud.githubusercontent.com/assets/1413538/18110111/a0fbb140-6eca-11e6-8a2a-cc0c8f9f8324.png)

**Comment by briandrawert** [comment]
When changing the "Select mapper to visualize", and "Select reducer to visualize", any change resets the view to the top of the page.  Should not scroll the page.

**Comment by bbbales2** [comment]
>> When changing the "Select mapper to visualize", and "Select reducer to visualize", any change resets the view to the top of the page. Should not scroll the page.

I don't get this behavior in Chrome or Firefox in Ubuntu. Not saying it doesn't exist though haha. Could you check all your browsers to see if this is particular to one?
