### ISSUE TITLE
Stderr and Stdout currently not handled in qsub branch

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#658]
Check in parametersweep.py

**Comment by bbbales2** [comment]
This might also require updating how the error codes and stuff are handled in status.py for qsub

**Comment by aviral26** [comment]
This issue deals with the propagation of any errors that may happen while a StochSS job is running on the cluster. The code that deals with this is in status.py. I haven't worked with that code at all. @bbbales2 do you know how we check for the log files to update the stderr/stdout that's displayed to the user?

**Comment by briandrawert** [comment]
addressed in 915739fe2082672404a51c4ca5c11b3eb05b306d
