### ISSUE TITLE
qsub branch: not handling invalid keys correctly on old flex cloud page

### ISSUE THREAD

**Issue by bbbales2** [StochSS/stochss#660]
It's possible to upload a private key that is invalid. This causes problems when starting and stopping the flex cloud computers (requests for passwords to the invalid keyfile show up in the terminal)

**Comment by aviral26** [comment]
The old flex cloud page is not a part of the current qsub branch, so do we still care about this?

**Comment by briandrawert** [comment]
I thought this might still be relevant.  If we upload a invalid key to the cluster environment, what is that behavior?

**Comment by aviral26** [comment]
Currently, there are no checks in place for invalid keys. So the SSH connection will simply fail on running a job and the user will see that error.

**Comment by briandrawert** [comment]
Errors not propagate to the user, in c74a0d1f1170af48eeb5e6f37c3979bba25cf86b
