### ISSUE TITLE
qsub branch: Permissions not set on uploaded SSH keys

### ISSUE THREAD

**Issue by aviral26** [StochSS/stochss#661]
The uploaded SSH keys from the Flex Cloud Page (and the Cluster Node Information Page) should have their permissions set to 0600.

**Comment by aviral26** [comment]
The keys are uploaded here: https://github.com/StochSS/stochss/blob/develop/app/static/js/cluster_credentials.js#L125

We POST to the FileServer URL to upload the key. I think the handler for this is fileserver.py but I'm not completely sure how it's working. @bbbales2 do you know how we can edit the permission of the uploaded file here?

**Comment by aviral26** [comment]
Is this the place we set the permissions? https://github.com/StochSS/stochss/blob/develop/app/handlers/fileserver.py#L102

**Comment by briandrawert** [comment]
addressed by 47cae003959550e46db82a32c01f207f2ea709bb
