### ISSUE TITLE
SBML import for Biomodels database

### ISSUE THREAD

**Issue by ahellander** [StochSS/stochss#72]
The Model editor can have a page that lets the user import curated (only curated) models from Biomodels database.

http://www.ebi.ac.uk/biomodels-main/webservices

This requires SBML import functionality to be added, and we need a way to filter the models from the database in such a way that only models that the solvers (StochKit)  can deal with can be imported. 

I think making this issue a priority will be good for thinking about units, SSA->ODE transitions in the Model Editor, etc.

**Comment by bbbales2** [comment]
This is implemented for 1.4 in branch sbml (https://github.com/StochSS/stochss/tree/sbml)

**Comment by bbbales2** [comment]
I made an attempt at this again in 1.6: https://github.com/StochSS/stochss/commit/a5eeec1a46cc7c5b07b7a8f17e3cf182a600899c .

For this import page, I require the user to say whether they are importing the model as a concentration or a population. I'm not sure how to do this translation automatically.

**Comment by briandrawert** [comment]
SBML import added in https://github.com/StochSS/stochss/pull/368
