### ISSUE TITLE
File not found error in converted Jupyter notebooks

### ISSUE THREAD

**Issue by jdreeve** [StochSS/stochss#778]
Jupyter notebooks created by StochSS Convert to Notebook feature produce file not found error when searching for makefile. 

To replicate:
-Convert any model to Jupyter notebook
-Run the first three code blocks
-Running fourth code block produces:
   FileNotFoundError: [Errno 2] No such file or directory: 'make': 'make'

Looks like this occurs when compile(self) in the C solver tries to access a makefile.
Full error output in attached .txt file.
[make_file_not_found.txt](https://github.com/StochSS/stochss/files/4023988/make_file_not_found.txt)

**Comment by BryanRumsey** [comment]
This was a qinikube issue where gcc and make were not installed
