### ISSUE TITLE
I can impersonate another user on https://app.stochss.org/ by guessing their email address

### ISSUE THREAD

**Issue by benblamey** [StochSS/stochss#805]
There seems to be a check that *someone* is logged on, but there does not seem to be a check that the person logged on has the same email address.

If I log on as ben.blamey@gmail.com
I can access https://app.stochss.org/user/blamey.ben@gmail.com/notebooks/Examples/Toggle_Switch/Toggle_Switch.ipynb
....All good

But, if I then try:
https://app.stochss.org/user/joe.bloggs@gmail.com

I can read/write/edit files as if I am logged on as them.

**Comment by BryanRumsey** [comment]
Resolved by PR #820
