### ISSUE TITLE
https://app.stochss.org - Directories appear when using space in filename

### ISSUE THREAD

**Issue by benblamey** [StochSS/stochss#808]
Created a model with name "hi this is ben", and get a spurious directory tree...

<img width="353" alt="Screen Shot 2020-04-08 at 11 26 58" src="https://user-images.githubusercontent.com/782539/78768251-f79e8e80-798b-11ea-919a-36a6bd6fa38b.png">

**Comment by BryanRumsey** [comment]
Addressed in PR #813
